import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const ritten = trpc.useQuery(["rit.getAll"]);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <table className="w-full divide-y divide-gray-300 shadow-sm focus-within:border-indigo-300 focus-within:ring-8 ring-offset-8 focus-within:ring-indigo-200 focus-within:ring-opacity-50 rounded-md">
          <thead className="bg-gray-50">
            <tr>
              <th
                scope="col"
                className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 rounded-tl-md"
              >
                Datum
              </th>
              <th
                scope="col"
                className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900"
              >
                Duur
              </th>
              <th
                scope="col"
                className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"
              >
                Afstand
              </th>
              <th
                scope="col"
                className="px-3 py-3.5 text-center text-sm font-semibold text-gray-900"
              >
                Calorieën
              </th>
              <th
                scope="col"
                className="px-3 py-3.5 text-center text-sm font-semibold text-gray-900 rounded-tr-md"
              >
                Weerstand
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200 bg-white">
            <tr>
              <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-semibold text-gray-900 sm:pl-6">
                1
              </td>
              <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                Norma Nova
              </td>
              <td className="whitespace-nowrap px-3 py-4 text-sm">
                norma@example.com
              </td>
              <td className="whitespace-nowrap px-3 py-4 text-sm">
                <span className="flex justify-center">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5 text-green-500"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fillRule="evenodd"
                      d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                      clipRule="evenodd"
                    />
                  </svg>
                </span>
              </td>
              <td className="py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                <div
                  className="inline-block text-left"
                  x-data="{ menu: false }"
                ></div>
              </td>
            </tr>
            <tr>
              <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-semibold text-gray-900 sm:pl-6">
                2
              </td>
              <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                Oscar Tellez
              </td>
              <td className="whitespace-nowrap px-3 py-4 text-sm">
                oscar@example.com
              </td>
              <td className="whitespace-nowrap px-3 py-4 text-sm">
                <span className="flex justify-center">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5 text-red-500"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fillRule="evenodd"
                      d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z"
                      clipRule="evenodd"
                    />
                  </svg>
                </span>
              </td>
              <td className="py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                <div
                  className="inline-block text-left"
                  x-data="{ menu: false }"
                ></div>
              </td>
            </tr>
            {ritten?.data?.map((rit, i) => {
              let roundl = ritten.data.length - 1 === i ? "rounded-bl-md" : "";
              let roundr = ritten.data.length - 1 === i ? "rounded-br-md" : "";
              return (
                <tr
                  key={rit.id}
                  className="even:bg-slate-50 hover:bg-slate-200"
                >
                  <td
                    className={`whitespace-nowrap py-4 pl-4 pr-3 text-sm font-semibold text-gray-900 sm:pl-6 ${roundl}`}
                  >
                    <Link href={`/edit/${rit.id}`}>
                      <a>{rit.date.toDateString()}</a>
                    </Link>
                  </td>
                  <td className="whitespace-nowrap px-3 py-4 text-sm">
                    {new Intl.NumberFormat("nl-BE", {
                      style: "unit",
                      unit: "minute",
                      unitDisplay: "short",
                    }).format(rit.duration)}
                  </td>
                  <td className="whitespace-nowrap px-3 py-4 text-sm">
                  {new Intl.NumberFormat("nl-BE", {
                      style: "unit",
                      unit: "kilometer",
                      unitDisplay: "short",
                    }).format(rit.distance / 1000)}
                  </td>
                  <td className="whitespace-nowrap px-3 py-4 text-sm">
                    {rit.calories}
                  </td>
                  <td
                    className={`whitespace-nowrap px-3 py-4 text-sm ${roundr}`}
                  >
                    {rit.resistance}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </main>
    </>
  );
};

export default Home;
